# Generated by Django 3.2.9 on 2021-11-09 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.IntegerField(default=0, verbose_name='latitude')),
                ('longitude', models.IntegerField(default=0, verbose_name='longitude')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('category', models.ManyToManyField(to='food_points.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.CharField(max_length=5, verbose_name='opened time')),
                ('closed', models.CharField(max_length=5, verbose_name='closed time')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(verbose_name='comment')),
                ('note', models.IntegerField(verbose_name='point note')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_points.point')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='time',
            field=models.ManyToManyField(to='food_points.Time'),
        ),
    ]
