# Generated by Django 3.2.9 on 2021-11-09 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='title',
            field=models.CharField(default='Heure', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
