# Generated by Django 3.2.9 on 2021-11-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_points', '0002_auto_20211109_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='time',
            name='opened',
        ),
        migrations.RemoveField(
            model_name='time',
            name='title',
        ),
        migrations.AddField(
            model_name='time',
            name='hours',
            field=models.CharField(default='7h à 12h', max_length=20, verbose_name='opened hours'),
            preserve_default=False,
        ),
    ]
