# Generated by Django 3.2.9 on 2021-11-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_points', '0003_auto_20211109_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.CharField(max_length=200),
        ),
    ]
