# Generated by Django 3.2.9 on 2021-11-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_points', '0004_auto_20211109_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point_disponibility',
            field=models.BooleanField(default=False),
        ),
    ]
