# Generated by Django 3.2.9 on 2022-01-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_points', '0007_auto_20211109_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicity',
            name='publicity_disponibility',
            field=models.BooleanField(default=True, verbose_name='disponibility'),
        ),
    ]
