# Generated by Django 3.2.9 on 2022-01-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_points', '0008_alter_publicity_publicity_disponibility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicity',
        ),
    ]
