# Generated by Django 3.2.9 on 2022-01-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_points', '0009_delete_publicity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='publicities')),
                ('url', models.URLField(verbose_name='publicity website url')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='modification date')),
                ('publicity_disponibility', models.BooleanField(default=True, verbose_name='disponibility')),
            ],
        ),
    ]
