# Generated by Django 3.2.9 on 2022-01-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_points', '0010_publicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='point',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
