# Generated by Django 3.2.9 on 2022-01-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_points', '0011_auto_20220127_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='food_point_images')),
                ('image2', models.ImageField(upload_to='food_point_images')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('point_disponibility', models.BooleanField(default=True, verbose_name='disponibility')),
                ('category', models.ManyToManyField(to='food_points.Category')),
                ('time', models.ManyToManyField(to='food_points.Time')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(verbose_name='comment')),
                ('note', models.IntegerField(verbose_name='point note')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_points.point')),
            ],
        ),
    ]
